### ISSUE TITLE
异步操作数据库的问题

### ISSUE THREAD

**Issue by cccfly-bake** [MrZhousf/EasyDB#1]
您好情况是这样的，我在代码用数据库写了递归，
`    public void getCheckDownLoadFile(List<FileListModel> list) {
        for (int i = 0; i < list.size(); i++) {
            final FileListModel model = list.get(i);
            if (model.getType() != 1) {
                mDownLoadList.add(list.get(i));
            } else {
                mFileModeDao.asyncTask(new EasyRun<List<FileListModel>>() {
                    @Override
                    public List<FileListModel> run() throws Exception {
                        return mFileModeDao.query(WhereInfo.get().equal("parentId", model.getFileId()));
                    }

                    @Override
                    public void onMainThread(List<FileListModel> data) throws Exception {
                        if (data != null && !data.isEmpty()) {
                            getCheckDownLoadFile(data);
                        }
                    }
                });
            }
        }
    }`
在UI线程去递归的时候，但是会跳出这个方法，执行一行UI线程中的代码，之后才会继续执行递归方法体。
代码可能有点乱，请见谅。

**Comment by MrZhousf** [comment]
“执行一行UI线程中的代码，之后才会继续执行递归方法体”，执行一行UI线程中的代码具体指的是哪行代码？递归方法中包含了新线程，对于getCheckDownLoadFile方法建议做同步

**Comment by cccfly-bake** [comment]
![image](https://cloud.githubusercontent.com/assets/15817271/21791246/787cdef0-d71c-11e6-9e8d-527a9f7c593e.png)
![image](https://cloud.githubusercontent.com/assets/15817271/21791270/92e53a6c-d71c-11e6-9eab-2968946d6b31.png)

**Comment by MrZhousf** [comment]
看了你的代码逻辑出现这种情况是正常的，因为你的递归方法里采用了子线程，所以外部调用递归方法时不会等到递归结束，你可以了解下Java的多线程操作。

**Comment by cccfly-bake** [comment]
看了看线程池和同步，异步，不知道怎么改这段代码了 - - ，囧，那我使用同步是在开一个子线程。在子线程中查完之后再去递归吗？

**Comment by MrZhousf** [comment]
可以

**Comment by cccfly-bake** [comment]
大概意思我明白了，我先写一下试试，谢谢。
